---
- name: Create a Windows Server VM from template
  hosts: localhost
  #We do not necessarily need to collect facts about our localhost so gather_facts=false
  gather_facts: no
  #Next line include the file that contains the variables:
  pre_tasks:
     #vars.yml : file that includes all variables like vcenter_ip,vcenter_username
   -  vars.yml
   -  authentification-vmware.yml
  tasks:
   
  - name: create folder
    community.vmware.vcenter_folder:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter_name: "{{ vcenter_datacenter }}"
        folder_name: "{{ vcenter_destination_folder }}"
        folder_type: vm
        state: present
   #----------------Task1---------------------
    
  - name: Clone from template
    vmware_guest:
         hostname: "{{ vcenter_ip}}"
         username: "{{ vcenter_username }}"
         password: "{{ vcenter_password }}"
         #ssl is a security standard tech for establishing  an encrypted link btwn a server & a client
         #next line we will turn off the ssl certifaction
         validate_certs: no
         #folder: dest folder,path to place datastore cluster in.the folder should include the datacenter
         folder_name: "{{ vcenter_destination_folder }}"
         name: new_vm
         template: nom_du_modèle
         datacenter: "{{ datacenter_name }}"
         cluster: "{{ cluster_name }}"
         #cluster :collection of datastores
         #customization : we use it for OS customization when we clone vm from template
         #The customization is related to vCenter version 
         customization:
             autologon: true 
             #VM name
             hostname: "{{ server }}"
             dns_servers:
              - "{{ dns_server }}"
             domain: "domain_name"
             joindomain: "domain_name"
             domainadmin: "admin"
             domainadminpassword: "admin"
             #runonce: list of cmds to run at first user logon(specific to windows customization) et il est utilisé pour executer une tache une seule fois 
             runonce:
             # I don't know what to add here 
         wait_for_customization: yes 
         hardware: 
           memory_mb: "{{ memory_mb }}"
           num_cpus: "{{ num_cpus }}"
           #hotadd_cpu: ajouter cpu quand la VM est démarrée
           hotadd_cpu: "{{ hot_add_cpu | default('True') }}"
           hotremove_cpu: "{{ hot_remove_cpu | default('True') }}"
           hotadd_memory:  "{{ hot_add_memory | default('False') }}"
           
           #I added these lines
           cpu_limit : "{{ cpu_limit_inMHz }}"
           mem_limit: "{{ mem_limit_in_MB }}"
         networks:
          - name: "{{ network_name }}"
            type: static 
            ip: "{{ network_ip }}"
            gateway: "{{ network_gateway }}"
            netmask: "{{ network_mask }}"
            domain:  "domain_name"
            dns_servers:
              - "{{ dns_server }}"
              #the next line means: Wait until vCenter detects an IP address for the virtual machine
         wait_for_ip_address: true 
         
   #----------------Task2---------------------    
  - name: Add new disk for the VM
    vmware_guest_disk: 
    #First we need to establish the connection with the VMware vCenter (hostname,user,psswd,validate_certs)
       hostname: "{{ vcenter_ip}}"
       username: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
       datacenter: "{{ datacenter_name }}"
       validate_certs: no
       name: "{{ server | upper}}"
       disk: 
        -size_gb:  "{{ disk_size }}"
         #number of scsi bus (or scsi_controller)
         type: "{{ vm_disk_type }}"
         #The name of datastore which will be used for the disk
         datastore: "{{ vm_disk_datastore }}"
         state: present
         scsi_controller: "{{ vm_disk_scsi_controller }}"
         unit_number:  "{{ vm_disk_unit_number }}"
         scsi_type: "{{ vm_disk_scsi_type }}"
    #delegate_to : pour spécifier dans quel machine il faut executer "the task"     
    delegate_to: localhost 
    #Register infos of the disk
    register: disk_facts
    
    
    #After finishing the creation of the vm we need to power on the vm to install vm-tools
    - name: Power on new VM
      vmware_guest_powerstate:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        name: "{{ server }}"
        state: powered_on
    
    #Installing vmware tools for Windows Server
    - name: 
  
    
    
            
           

           
         
         
