---
- name: Windows Updates
  hosts: all 
  tasks: 
  - name: install Updates
    win_updates:
       category_names: 
           - CriticalUpdates
           - SecurityUpdates
           - UpdateRollups
           - Tools 
           # we can add other updates if needed
       accept_list:
          - KB123345
          - KB579867
       state: installed
       reboot: true  
       #role de log_path: win_updates ajoutera les progressions des MAJ au fichier spécifié
       log_path: C:\progress_file.txt
       
